---

- name: "default variable zetten als var leeg is"
  set_fact:
    rd_option_groupnames: "domain users"
    rd_option_groupnames2: "domain users"
- name: "Add user to group"
  win_domain_user:
    name: "{{ item }}"
    groups_action: "add"
    groups: "{{ (zinl_groupnames.split(',')) + (zinl_groupnames2.split(',')) }}"
  loop: "{{ zinl_username.split(',') }}"
