---
- name: install a lamp server 
  hosts: linux2
  become: yes
  gather_facts: yes
  tasks:
    - name: make sure we can connect
      ping:
    - name: install LAMP Server
      apt:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      with_items:
          - apache2
          - mysql-server
          - php
          - libapache2-mod-php
          - python-mysqldb

    - name: create the Apache2 web folder
      file:
        dest: "/var/www"
        state: directory
        mode: 0700
        owner: "www-data"
        group: "www-data"
      
    - name: setup apache2 modules
      command: a2enmod {{ item }} create=/etc/apache2/mods-enabled/ {{ item }}.load
      with_items:
        - deflater
        - expires
        - headers
        - macro
        - rewrite 
        - rax_clb_ssl
      
    - name: setp php modules
      apt:
        name: '{{ itemt }}'
        state: latest
        update_cahche: yes
      with_items:
        - php-ssh2
        - php-apcu
        - php-pear
        - php-curl
        - php-gd
        - php-imagick
        - php-mcrypt
        - php-mysql
        - php-json

    - name: remove mysql test database
      mysql_db: db=test state=absent login_user=root
      login_password="DBp@55w0rd"
    
    - name: restart mysql server
      service:
        name: mysql
        state: restarted

    - name: restart apache2
      service:
        name: apache2
        state: restarted