---
- name: "Add user to group"
  hosts: "domaincontroller"
  tasks:
  - name: "default variable zetten als var leeg is"
    set_fact:
      rd_option_groupnames: "domain users"
      rd_option_groupnames2: "domain users"
      rd_option_groupnames3: "domain users"
  - name: "Add user to group"
    win_domain_user:
      name: "{{ item }}"
      groups_action: "add"
      groups: "{{ rd_option_groupnames.split(',')  + (rd_option_groupnames2.split(',')) }}"
    loop: "{{ rd_option_username.split(',') }}"
