---
- hosts: domaincontroller
  tasks:
    - name: is the server alive
      win_ping:
    - name: create a new domain in a new forest
      win_domain:
        create_dns_delegation: no
        database_path: c:\Windows\NTDS
        dns_domain_name: ansible.local
        domain_mode: Win2012R2
        domain_netbios_name: ANSIBLE
        forest_mode: Win2012R2
        safe_mode_password: Corona@2021Hoogeveen
        sysvol_path: C:\Windows\SYSVOL
      register: domain_install
    - name: install rsat tools
      win_feature:
        name:
          - rsat

