---
 
- name: "New user"
  hosts: "domaincontroller"
  tasks:
    - name: "Check if the user exists"
      win_domain_user:
        name: "{{ rd_option_username }}"
        state: "query"
      register: "user_check"
    - name: "Fail if user is found"
      fail:
        msg: "'{{ user_check.name }}' already exists"
      when:
        - "user_check.state == 'present'"
    - set_fact:
        user_password: "aC{{ lookup('password', '/dev/null length=10 chars=digits') }}!"
    - name: "Create user"
      win_domain_user:
        name: "{{ rd_option_username }}"
        firstname: "{{ rd_option_firstname }}"
        surname: "{{ rd_option_surname }}"
        upn: "{{ rd_option_email }}"
        password: "{{ user_password }}"
        company: "{{ rd_option_company }}"
        state: "present"
        groups:
          - "Domain Users"
          - "Ansible users"
          - "Ansible users2"
        groups_action: "add"
        path: "OU=AnsibleUsers,DC=ansible,DC=local"
        attributes:
          mobile: "{{ rd_option_mobilephone }}"
          title: "{{ rd_option_functie }}"
          department: "{{ rd_option_department }}"
          physicalDeliveryOfficeName: "{{ rd_option_office }}"
          manager: "CN={{ rd_option_manager }},OU=AnsibleUsers,DC=ansible,DC=local"
          sAMAccountName: "{{ rd_option_username }}"
          displayName: " {{ rd_option_displaynaam }}"