---
- name: "remove users from group"
  hosts: "domaincontroller"
  tasks:
    - name: "remove users from group"
      win_domain_user:
        name: "{{ item }}"
        groups_action: "remove"
        groups: "{{ rd_option_groupnames.split(',') }}"
      loop: "{{ rd_option_username.split(',') }}"
