---
- name: create new user and add to group
  hosts: domaincontroller
  tasks:
    - name: create user and add to group
      win_domain_user:
        name: "{{ RD_OPTION_USERNAME }}" 
        firstname: "{{ RD_OPTION_FIRSTNAME}}" 
        surname: "{{ RD_OPTION_SURNAME }}" 
        company: "zinldc"
        password: "Corona@2021Hoogeveen"
        state: present
        path: "OU=AnsibleUsers,DC=ansible,DC=local"
        groups:
          - "Ansible Users"
          - "Ansible Users1"
          - "Ansible Users2"

        
        