---
- name: "create new user and add to group"
  hosts: "domaincontroller"
  tasks:
    - win_domain_user:
        name: "{{ name }}"
        firstname: "{{ firstname }}"
        surname: "{{ surname }}"
        username: "{{ username }}"
        company: "ansible"
        password: "Corona@2021Hoogeveen"
        state: "present"
        path: "OU=AnsibleUsers,DC=ansible,DC=local"
        groups:
          - "Ansible Users"
          - "Ansible Users1"
          - "Ansible Users2"
